<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="org.testngsmart.A" tests="6" time="0.032" ignored="0" failures="1" timestamp="10 Jan 2024 16:28:21 GMT" skipped="3" hostname="DESKTOP-D0IPNU4" errors="0">
  <testcase name="tc11" time="0.021" classname="org.testngsmart.A"/>
  <testcase name="tc13" time="0.001" classname="org.testngsmart.A">
    <skipped/>
  </testcase> <!-- tc13 -->
  <testcase name="tc12" time="0.004" classname="org.testngsmart.A"/>
  <testcase name="tc13" time="0.002" classname="org.testngsmart.A">
    <skipped/>
  </testcase> <!-- tc13 -->
  <testcase name="tc13" time="0.002" classname="org.testngsmart.A">
    <failure type="java.lang.AssertionError" message="Verify the assert expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Verify the assert expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testngsmart.A.tc13(A.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- tc13 -->
  <testcase name="tc13" time="0.002" classname="org.testngsmart.A">
    <skipped/>
  </testcase> <!-- tc13 -->
</testsuite> <!-- org.testngsmart.A -->
